stages:
  - ansible-lint
ansible-lint:
  stage: ansible-lint
  image: marcinbojko/pipetools-ansible
  services:
    - docker:20.10-dind
  before_script:
    - yamllint --version
    - ansible-lint --version
  script:
    - yamllint -c ./.yamllint ./tasks/*.yml
    - yamllint -c ./.yamllint *.yaml
    - ansible-lint -v ./tasks/*.yml
    - ansible-lint -v linux_mint.yaml
  tags:
    - docker
    - ansible
