stages:
  - ansible-lint
ansible-lint:
  stage: ansible-lint
  image: $PIPELINE_IMAGE:$PIPELINE_IMAGE_TAG
  retry: 2
  services:
    - docker:20.10-dind
  before_script:
    - yamllint --version
    - ansible-lint --version
  script:
    - echo "Running on $PIPELINE_IMAGE:$PIPELINE_IMAGE_TAG"
    - yamllint -c ./.yamllint ./tasks/*.yml
    - yamllint -c ./.yamllint *.yaml
    - ansible-lint -v ./tasks/*.yml
    - ansible-lint -v linux_mint.yaml
  tags:
    - docker
    - ansible
