- name: add_yubico_repo_key
  apt_key:
    keyserver: "{{ item.keyserver }}"
    state: present
    id: "{{ item.id }}"
  loop: "{{ yubico_repo_key }}"
  register: r_keys_yubico_repo_key
  retries: "{{ retries_count }}"
  delay: "{{ delay_time }}"
  until: r_keys_yubico_repo_key is success
  any_errors_fatal: true
  tags:
  - keys
  - task
  - yubico
- name: add_yubico_repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    codename: "{{ codename }}"
    filename: "{{ item.filename }}"
    mode: "0644"
  loop: "{{ yubico_repositories }}"
  retries: "{{ retries_count }}"
  delay: 3
  register: r_yubico_repositories
  until: r_yubico_repositories is success
  when: r_keys_yubico_repo_key is success
  any_errors_fatal: false
  tags:
  - repositories
  - task
  - yubico
- name: install_yubico_packages
  apt:
    name: "{{ item }}"
    state: "{{ install_state }}"
    update_cache: no
  loop: "{{ yubico_packages }}"
  retries: "{{ retries_count }}"
  delay: "{{ delay_time }}"
  register: r_yubico_packages
  until: r_yubico_packages is success
  when: r_yubico_repositories is success
  any_errors_fatal: false
  tags:
  - packages
  - task
  - yubico
# appimages
- name: download_yubico_files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ bin_path }}/{{ item.destination }}"
    mode: 0755
    force: yes
  loop: "{{ yubico_appimage }}"
  retries: "{{ retries_count }}"
  delay: "{{ delay_time }}"
  register: r_download_yubico_files
  until: r_download_yubico_files is success
  tags:
  - task
  - downloads
  - apps
  - yubico
- name: put_desktop_files_for_yubico
  copy:
    dest: /usr/share/applications
    src: "{{ item.desktop_file }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ yubico_appimage }}"
  when: item.desktop_file is defined and item.desktop_file | length >0
  any_errors_fatal: false
  register: r_put_yubico_desktop_files
  retries: "{{ retries_count }}"
  delay: "{{ delay_time }}"
  until: r_put_yubico_desktop_files is success
  tags:
  - task
  - downloads
  - apps
  - yubico
- name: refresh_desktop_database
  ansible.builtin.shell: update-desktop-database
  any_errors_fatal: false
  ignore_errors: true
  changed_when:
  tags:
  - task
  - downloads
  - apps
  - yubico
